# Generated by Django 3.2.12 on 2022-04-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220408_1449'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipesuser',
            managers=[
            ],
        ),
    ]
