# Generated by Django 3.2.12 on 2022-03-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import final_project.recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='Recipe Name')),
                ('ingredients', models.CharField(max_length=500, validators=[final_project.recipes.validators.validate_ingredients], verbose_name='Ingredients')),
                ('recipe_picture', models.ImageField(upload_to='mediafiles', verbose_name='Recipe Picture')),
                ('how_to_make', models.CharField(max_length=800, verbose_name='How To Make')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Salads', 'Salads'), ('Soups', 'Soups'), ('Appetizers', 'Appetizers'), ('Main dishes', 'Main dishes'), ('Desserts', 'Desserts'), ('Baked dishes', 'Baked dishes'), ('Other', 'Other')], max_length=12, verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
