# Generated by Django 3.2.12 on 2022-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=2800),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
